import moviePic from '../../images/moviePic.jpg';

const moviesList = [
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за БэнксиВ погоне за БэнксиВ погоне за БэнксиВ погоне за БэнксиВ погоне за БэнксиВ погоне за БэнксиВ погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
];

const savedMovies = [
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне погоне погоне погоне погоне погоне погоне',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
    {
        country: 'ФРАНЦИЯ',
        director: 'АУРЕЛИЯ РУВЬЕ, ШЕЙМАС ХЭЙЛИ',
        duration: 90,
        year: '2020',
        description: '',
        image: moviePic,
        trailer: '',
        thumbnail: moviePic,
        movieId: 123,
        nameRU: 'В погоне за Бэнкси',
        nameEN: 'Banksy Most Wanted',
    },
];

export { savedMovies, moviesList };
